
외워야 할 것 있음.
oop에서는 예외 처리가 있음.

주의 :
	catch(Exception e) {  }
	catch(ArithmeticException e) { }
	을 2개 사용하면 에러 발생.
	
	이유 : Exception 이 예외의 최상위 부모라서
			catch(ArithmeticException e)
			부분이 호출이 않되므로,
	
	에러 메시지 : 
		Unreachable catch block for ArithmeticException. 
		It is already handled by the catch block for Exception
	
주의: 
	catch(Exception e){ 
		e.printStackTrace(); //<--를 넣어 많이 사용한다.
	} 

주의 : catch가 여러개 있어도, 1개만 타고 빠져 나온다.

주의:
	try{
	}
	catch(Exception e) {
	}
	에서,
	질문 : 객체 생성도 안하고, Exception e 을 누가 넣어 주나?
	답변 : JVM 
		(실시간으로 에러 나는것은 JVM이 내보내 준다.
		실행시에 연산의 주체는 JVM 이므로)
	
용어 주의 :
	예외,Exception 
	에러와는 다름


### 주의: 예외 처리 위한 try ~ catch
	try catch 구문을 사용하면,
	JVM이  
	catch( Excption e ) 의 e를 전달해준다. 
	( --> catch 안의 부분을 호출해 준다.)
	catch( Excption e ) 부분도 하나의 오버로딩
	
	ex.
	try{
	
	}
	catch(Exception e){
		System.out.println(e.getMessage());
	}
	
### 주의 : null pointer exception
		String str = null;
	      System.out.println(str);   // null 출력
	      // 주의 : 이경우 exception임, 0 이 넘어 오지 않나봐.? 
	      int len = str.length();